import { MetadataRoute } from "next";

export const dynamic = "force-static";

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = "https://www.altplnepal.com";

  return [
    {
      url: `${baseUrl}/`,
      lastModified: "2026-02-11",
      changeFrequency: "weekly",
      priority: 1,
    },
    {
      url: `${baseUrl}/products/diagnostics/oct/maestro2/`,
      lastModified: "2026-02-11",
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${baseUrl}/products/diagnostics/oct/triton/`,
      lastModified: "2026-02-11",
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${baseUrl}/products/diagnostics/biometer/aladdin/`,
      lastModified: "2026-02-11",
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${baseUrl}/products/diagnostics/fundus-cameras/nw500/`,
      lastModified: "2026-02-11",
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${baseUrl}/products/diagnostics/fundus-cameras/trc-nw400/`,
      lastModified: "2026-02-11",
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${baseUrl}/products/diagnostics/fundus-cameras/trc-nw8series/`,
      lastModified: "2026-02-11",
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${baseUrl}/products/diagnostics/fundus-cameras/trc-50dx/`,
      lastModified: "2026-02-11",
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${baseUrl}/products/diagnostics/perimeters/henson-9000/`,
      lastModified: "2026-02-11",
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${baseUrl}/products/diagnostics/slit-lamps/sl-d301/`,
      lastModified: "2026-02-11",
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${baseUrl}/products/diagnostics/slit-lamps/sl-d2/`,
      lastModified: "2026-02-11",
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${baseUrl}/products/diagnostics/slit-lamps/sl-d701/`,
      lastModified: "2026-02-11",
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${baseUrl}/products/diagnostics/slit-lamps/sl-2g/`,
      lastModified: "2026-02-11",
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${baseUrl}/products/diagnostics/slit-lamps/sl-d4/`,
      lastModified: "2026-02-11",
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${baseUrl}/products/diagnostics/slit-lamps/dc-4/`,
      lastModified: "2026-02-11",
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${baseUrl}/products/diagnostics/axiallength/myah/`,
      lastModified: "2026-02-11",
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${baseUrl}/products/diagnostics/wavefront-analyzer/kr-1w/`,
      lastModified: "2026-02-11",
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${baseUrl}/products/diagnostics/specular-microscope/sp-1p/`,
      lastModified: "2026-02-11",
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${baseUrl}/products/examination/auto-refractometer/kr-1/`,
      lastModified: "2026-02-11",
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${baseUrl}/products/examination/auto-refractometer/kr-800series/`,
      lastModified: "2026-02-11",
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${baseUrl}/products/examination/auto-refractometer/rm-1/`,
      lastModified: "2026-02-03",
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${baseUrl}/products/examination/auto-refractometer/rm-800/`,
      lastModified: "2026-02-03",
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${baseUrl}/products/examination/topographer/ca-800/`,
      lastModified: "2026-02-11",
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${baseUrl}/products/examination/visual-acuity-chart/acp-8/`,
      lastModified: "2026-02-03",
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${baseUrl}/products/examination/visual-acuity-chart/mc-5-5s/`,
      lastModified: "2026-02-03",
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${baseUrl}/products/examination/visual-acuity-chart/pc-50series/`,
      lastModified: "2026-02-03",
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${baseUrl}/products/examination/lensmeter/solos/`,
      lastModified: "2026-02-11",
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${baseUrl}/products/examination/lensmeter/cl-300/`,
      lastModified: "2026-02-03",
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${baseUrl}/products/examination/lensmeter/lm-8-8c/`,
      lastModified: "2026-02-03",
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${baseUrl}/products/examination/tonometer/ct-800series/`,
      lastModified: "2026-02-11",
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${baseUrl}/products/examination/tonometer/trk-3-omnia/`,
      lastModified: "2026-02-11",
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${baseUrl}/products/examination/tonometer/ct-1-1p/`,
      lastModified: "2026-02-03",
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${baseUrl}/products/examination/tonometer/trk-2p/`,
      lastModified: "2026-02-03",
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${baseUrl}/products/examination/refraction-system/chronos/`,
      lastModified: "2026-02-11",
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${baseUrl}/products/examination/vision-tester/cv-5000series-pro/`,
      lastModified: "2026-02-11",
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${baseUrl}/products/examination/vision-tester/vt-10/`,
      lastModified: "2026-02-03",
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${baseUrl}/products/software/imagenet-6/`,
      lastModified: "2026-02-03",
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${baseUrl}/products/data-management/harmony/`,
      lastModified: "2026-02-03",
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${baseUrl}/products/treatment/photocoagulator/pascal-synthesis/`,
      lastModified: "2026-02-11",
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${baseUrl}/products/treatment/photocoagulator/hud-1/`,
      lastModified: "2026-02-03",
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${baseUrl}/products/treatment/photocoagulator/endpoint-management/`,
      lastModified: "2026-02-03",
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${baseUrl}/products/treatment/photocoagulator/pattern-scanning-laser-trabeculoplasty/`,
      lastModified: "2026-02-03",
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${baseUrl}/products/treatment/operation-microscopes/oms-800series/`,
      lastModified: "2026-02-11",
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${baseUrl}/products/treatment/operation-microscopes/oms-90/`,
      lastModified: "2026-02-03",
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${baseUrl}/products/treatment/iridex-products/iridex-PASCAL/`,
      lastModified: "2026-02-11",
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${baseUrl}/products/treatment/iridex-products/PASCAL-synthesis-twinstar/`,
      lastModified: "2026-02-03",
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${baseUrl}/products/treatment/iridex-products/oculight-series/`,
      lastModified: "2026-02-03",
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${baseUrl}/products/treatment/iridex-products/IQ532/`,
      lastModified: "2026-02-03",
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${baseUrl}/products/treatment/iridex-products/IQ577/`,
      lastModified: "2026-02-11",
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${baseUrl}/products/treatment/iridex-products/cyclo-G6/`,
      lastModified: "2026-02-03",
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${baseUrl}/company/aboutus/`,
      lastModified: "2026-02-03",
      changeFrequency: "yearly",
      priority: 0.9,
    },
    {
      url: `${baseUrl}/company/careers/`,
      lastModified: "2026-02-03",
      changeFrequency: "yearly",
      priority: 0.3,
    },
    {
      url: `${baseUrl}/company/inquiry/`,
      lastModified: "2026-02-03",
      changeFrequency: "yearly",
      priority: 0.2,
    },
    {
      url: `${baseUrl}/company/feedback/`,
      lastModified: "2026-02-03",
      changeFrequency: "yearly",
      priority: 0.2,
    },
    {
      url: `${baseUrl}/company/privacy/`,
      lastModified: "2026-02-03",
      changeFrequency: "yearly",
      priority: 0.1,
    },
    {
      url: `${baseUrl}/support/personalizedsupport/`,
      lastModified: "2026-02-03",
      changeFrequency: "yearly",
      priority: 0.4,
    },
    {
      url: `${baseUrl}/support/service/`,
      lastModified: "2026-02-03",
      changeFrequency: "monthly",
      priority: 0.4,
    },
    {
      url: `${baseUrl}/news/conferences/`,
      lastModified: "2026-02-03",
      changeFrequency: "monthly",
      priority: 0.5,
    },
    {
      url: `${baseUrl}/news/gallery/`,
      lastModified: "2026-02-03",
      changeFrequency: "monthly",
      priority: 0.5,
    },
  ];
}
